### PR TITLE
Commands to new version

### PR DESCRIPTION
**Pull request by AugustoPeres**

### CODE REVIEW

**Review by IvanPombo — APPROVED** [review]
Do you have proof-of-work?

**Review by IvanPombo — CHANGES_REQUESTED** [review]
Actually, the docs should also be changed. Please go over them.

**Comment by AugustoPeres** [comment]
Screenshot 2024-01-24 at 17 31 37

**Review by IvanPombo — APPROVED** [review]
LGTM!

**Comment by AugustoPeres** [comment]
> LGTM!

Could you test on your side to test?

**Comment by IvanPombo** [comment]
> > LGTM!
> 
> Could you test on your side to test?

Good to go! Working Nicely!!

**Pull request merged**
